name: Deploy Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy New Version # todo update when prod env is ready
        run: "aws autoscaling start-instance-refresh --auto-scaling-group-name smbd-scaler --preferences '{\"InstanceWarmup\": 300, \"MinHealthyPercentage\": 50, \"SkipMatching\": false}'"